description = "Initializ Buildpack for Go"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:1.0.8"
  version = "1.0.8"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/nodejs:0.0.1"
  version = "1.0.8"

[lifecycle]
  version = "0.19.4"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.0.8"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/nodejs"
    version = "0.0.1"

[stack]
  build-image = "initializbuildpacks/securepacks-build:latest"
  id = "Initializ Distroless Stack"
  run-image = "initializbuildpacks/securepacks-run:latest"
  run-image-mirrors = []
