description = "Initializ Buildpack for Go"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:1.0.8"
  version = "1.0.8"

[lifecycle]
  version = "0.19.3"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.0.8"

[stack]
  build-image = "docker.io/initializbuildpacks/go-securepack-build:0.0.1"
  id = "Initializ Distroless Stack"
  run-image = "docker.io/initializbuildpacks/go-securepack-run:latest"
  run-image-mirrors = []
