description = "Initializ Distroless base image with buildpacks for Go"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:1.0.7"
  version = "1.0.7"

[lifecycle]
  version = "0.19.3"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.0.7"

[stack]
  build-image = "docker.io/initializbuildpacks/securepacks-build:1.0.3"
  id = "Initializ Distroless Stack"
  run-image = "docker.io/initializbuildpacks/securepacks-run:latest"
  run-image-mirrors = []
