description = ""

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:1.21.11"
  version = "1.21.11"

[lifecycle]
  version = "0.19.6"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.21.11"

[stack]
  build-image = "docker.io/initializbuildpacks/go-securepack-build:9.9.9"
  id = "Initializ Distroless Stack"
  run-image = "docker.io/initializbuildpacks/go-securepack-run:latest"
  run-image-mirrors = []
