description = "Initializ Buildpack for Go, Nodejs"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:1.21.19"
  version = "1.21.19"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/nodejs:2.2.4"
  version = "2.2.4"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/procfile:5.6.18"
  version = "5.6.18"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/web-servers:1.0.8"
  version = "1.0.8"

[lifecycle]
  version = "0.19.7"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.21.19"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/web-servers"
    version = "1.0.8"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/nodejs"
    version = "2.2.4"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    version = "5.6.18"

[stack]
  build-image = "docker.io/initializbuildpacks/go-securepack-build:9.9.9"
  id = "Initializ Distroless Stack"
  run-image = "docker.io/initializbuildpacks/securepacks-run:latest"
  run-image-mirrors = []
